/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.binarytree.tester;

import org.junit.Test;

import com.blz.binarytree.controller.BinarySearchTree;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class BinarySearchTreeTest {
	@Test
	public void testGiven3NumbersWhenaddedToBSTShouldReturnSize3() {
		BinarySearchTree<Integer> binaryTree = new BinarySearchTree<Integer>();
		binaryTree.addKey(56);
		binaryTree.addKey(70);
		binaryTree.addKey(30);

		int size = binaryTree.getSize();
		Assert.assertEquals(3, size);
	}
}
