/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.binarytree.tester;

import org.junit.Test;

import com.blz.binarytree.controller.BinarySearchTree;

import junit.framework.Assert;

import static org.junit.Assert.*;

public class BinarySearchTreeTest {
	@Test
	public void testGiven3NumbersWhenaddedToBSTShouldReturnSize3() {
		BinarySearchTree<Integer> binaryTree = new BinarySearchTree<Integer>();
		binaryTree.addKey(56);
		binaryTree.addKey(70);
		binaryTree.addKey(30);

		int size = binaryTree.getSize();
		Assert.assertEquals(3, size);
	}

	@Test
	public void testGivenNumbersWhenaddedToBSTShouldReturnCorrectSize() {
		BinarySearchTree<Integer> binaryTree = new BinarySearchTree<Integer>();
		binaryTree.addKey(56);
		binaryTree.addKey(70);
		binaryTree.addKey(30);
		binaryTree.addKey(40);
		binaryTree.addKey(22);
		binaryTree.addKey(11);
		binaryTree.addKey(3);
		binaryTree.addKey(16);
		binaryTree.addKey(60);
		binaryTree.addKey(95);
		binaryTree.addKey(65);
		binaryTree.addKey(63);
		binaryTree.addKey(67);
		int size = binaryTree.getSize();
		Assert.assertEquals(13, size);
	}
	@Test
	public void testWhenAddedElemetSearchedShouldReturnTrue() {
		BinarySearchTree<Integer> binaryTree = new BinarySearchTree<Integer>();
		binaryTree.addKey(56);
		binaryTree.addKey(70);
		binaryTree.addKey(30);
		binaryTree.addKey(40);
		binaryTree.addKey(22);
		binaryTree.addKey(11);
		binaryTree.addKey(3);
		binaryTree.addKey(16);
		binaryTree.addKey(60);
		binaryTree.addKey(95);
		binaryTree.addKey(65);
		binaryTree.addKey(63);
		binaryTree.addKey(67);
		int searchedKey=binaryTree.searchKey(63);
		Assert.assertEquals(63, searchedKey);
	}
}
